### ISSUE TITLE
Bug: Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by rangerscience** [getstation/electron-chrome-extension#63]
Replicated [here](https://github.com/rangerscience/electron-extensions/commit/4fb42feec1bf12e11848353e7c1f72d7be689cb9), just `yarn install` and `yarn start`

Node version v13.0.1, MacOS 10.14.5

This is a barebones Electron app that does zilch else; only `yarn install electron-chrome-extension`. Adding this module breaks `yarn start` with the following error on console:

```
$ yarn start                                                                                                                                                                           
yarn run v1.17.3
warning package.json: No license field
$ electron .
App threw an error during load
Error: Cannot find module 'tslib'
Require stack:
- ./electron-hello-world/node_modules/electron-chrome-extension/lib/browser/index.js
- ./electron-hello-world/node_modules/electron-chrome-extension/index.js
- ./electron-hello-world/main.js
- ./electron-hello-world/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
-
at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7615:16)
at Module._load (internal/modules/cjs/loader.js:622:27)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Module.require (internal/modules/cjs/loader.js:775:19)
at require (internal/modules/cjs/helpers.js:68:18)
at Object.<anonymous> (/Users/nickbarone/ecosystems/comake/electron-hello-world/node_modules/electron-chrome-extension/lib/browser/index.js:3:17)
at Module._compile (internal/modules/cjs/loader.js:880:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
```

**Comment by rangerscience** [comment]
`yarn install tslib` appears to fix this (there's a subsequent error), although it should be added to the library dependencies.

**Comment by rangerscience** [comment]
I'm no longer working on the project that this came up in.
