### ISSUE TITLE
TypeError: ECx.load is not a function

### ISSUE THREAD

**Issue by rangerscience** [getstation/electron-chrome-extension#64]
Replicated [here](https://github.com/rangerscience/electron-extensions/commit/1a4ea518c391e3967ac4c73bd01d61a517d5ca84); `yarn install`

```
$ yarn start
yarn run v1.17.3
$ electron .
(node:58020) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:58020) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:58020) UnhandledPromiseRejectionWarning: TypeError: ECx.load is not a function
    at App.createWindow (./electron-hello-world/main.js:23:13)
    at App.emit (events.js:208:15)
```

**Comment by rangerscience** [comment]
Aha, this appears to be my own inexperience with JS/TS/Node, as it's apparently resolved by doing:
```
const ECx = require('electron-chrome-extension').default
```
instead of:
```
const ECx = require('electron-chrome-extension')
```

**Comment by magne4000** [comment]
There is also a `allowSyntheticDefaultImports` in the compilerOptions to fix that. See https://www.typescriptlang.org/docs/handbook/compiler-options.html
