### ISSUE TITLE
Cannot read property 'origin' of undefined

### ISSUE THREAD

**Issue by rangerscience** [getstation/electron-chrome-extension#65]
Stack trace:
```
    at session.webRequest.onBeforeSendHeaders.origin (./electron-hello-world/node_modules/electron-chrome-extension/lib/browser/engine/webRequest.js:86:32)
    at ./electron-hello-world/node_modules/electron-better-web-request/lib/electron-better-web-request.js:177:17
    at new Promise (<anonymous>)
    at Object.apply (./electron-hello-world/node_modules/electron-better-web-request/lib/electron-better-web-request.js:175:22)
    at defaultResolver (./electron-hello-world/node_modules/electron-better-web-request/lib/electron-better-web-request.js:9:17)
    at BetterWebRequest.<anonymous> (./electron-hello-world/node_modules/electron-better-web-request/lib/electron-better-web-request.js:151:40)
    at Generator.next (<anonymous>)
    at ./electron-hello-world/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (./electron-hello-world/node_modules/tslib/tslib.js:106:16)
```

Which is [here](https://github.com/getstation/electron-chrome-extension/blob/a73e538777457075640ad3bb3ede567d42c77d1c/src/browser/engine/webRequest.ts#L112) (I think), and you can find the reproducing project [here](https://github.com/rangerscience/electron-extensions), electron-chrome-extension branch.

It looks like ECX is expecting headers to be set, but it's not clear to me why it's expecting that, or where that's supposed to happen either in this library or in the usage code.

**Comment by holmberd** [comment]
Electron +7 contained underlying changes to the NET modules and subsequently webRequests.

**Comment by rangerscience** [comment]
I'm no longer working on this project, so going to close ticket.
