### ISSUE TITLE
TypeError: process.electronBinding is not a function

### ISSUE THREAD

**Issue by michadasis** [getstation/electron-chrome-extension#99]
After installing tslib which is a dependency and running npm start, it gets me the error below.
I used `const ECx = require("electron-chrome-extension").default;` import didn't work for me any possible way this is a mistake on my end?
`App threw an error during load
TypeError: process.electronBinding is not a function
    at Object.<anonymous> (/home/john/Desktop/genericsoundcloudclient/node_modules/electron-chrome-extension/lib/browser/chrome-extension.js:2:39)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/john/Desktop/genericsoundcloudclient/node_modules/electron-chrome-extension/lib/browser/engine/api.js:5:28)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: process.electronBinding is not a function
    at Object.<anonymous> (/home/john/Desktop/genericsoundcloudclient/node_modules/electron-chrome-extension/lib/browser/chrome-extension.js:2:39)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/john/Desktop/genericsoundcloudclient/node_modules/electron-chrome-extension/lib/browser/engine/api.js:5:28)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:23165) UnhandledPromiseRejectionWarning: TypeError: process.electronBinding is not a function
    at Object.<anonymous> (/home/john/Desktop/genericsoundcloudclient/node_modules/electron-chrome-extension/lib/browser/chrome-extension.js:2:39)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/john/Desktop/genericsoundcloudclient/node_modules/electron-chrome-extension/lib/browser/engine/protocol.js:12:28)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:23165) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by aaaddress1** [comment]
![image](https://user-images.githubusercontent.com/8559056/210302368-cb738873-8bc7-41bf-885b-3911e2d90d97.png)
got the same issue here.
